# Generated by djereo v3.15.0-2-g13b2d9b using Django 5.2

from django.db import migrations

import users.models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_userprofile"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="authuser",
            managers=[
                ("objects", users.models.AuthUserManager()),
            ],
        ),
    ]
