# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v3.14.0-1-g47d6f20
_src_path: djereo
author_email: alberto.moronh@gmail.com
author_name: Alberto Morón Hernández
django_version: '5.2'
is_github_project: true
min_python_version: '3.13'
postgres_version: '17'
project_name: testdjereo
use_django_waffle: true
use_htmx: true
