# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v3.5.0-7-g67de8a5
_src_path: djereo
author_email: alberto.moronh@gmail.com
author_name: Alberto Morón Hernández
django_version: '5.1'
is_github_project: true
postgres_version: '17'
project_name: testdjereo
python_version: '3.12'
use_django_waffle: true
use_htmx: true
