config:
  default: true

  ignores:
    # on account of this being generated automatically by 'Release Please'
    - "CHANGELOG.md"
  # per-rule settings in alphabetical order
  # https://github.com/DavidAnson/markdownlint/tree/main/doc
  code-block-style:
    style: "fenced"                 # MD046
  line-length:                      # MD013
    code_blocks: false
    line_length: 100
    tables: false
  link-fragments:                   # MD051
    ignore_case: true
  no-duplicate-heading:             # MD024
    # allow duplicate headings in eg. CHANGELOG.md
    siblings_only: true

fix: true

ignores:
  # on account of this being generated automatically by 'Release Please'
  - "CHANGELOG.md"
