# On Tag pipeline
# Runs when a semver tag is pushed up to GitHub.
#
# Prerequisites:
#   - GH secrets (<https://github.com/albertomh/testdjereo/settings/secrets/actions>):
#     - `DO_VPS_IP`: IPv4 address of the Digital Ocean Droplet (VPS)
#     - `TESTDJEREO_BOT_PRIVATE_KEY`: private key for 'testdjereo_bot', `.ssh/testdjereo_bot_ed25519`
#     - `SERVICE_URL`: URL for the web service (WITHOUT trailing slash!)
name: on-tag

on:
  push:
    # run this workflow only if the tag matches the format 'v<semver>'
    tags:
      - 'v*.*.*'

jobs:
  pre_commit:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/pre-commit

  test:
    needs:
      - pre_commit
    runs-on: ubuntu-24.04
    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_DB: testdjereo
          POSTGRES_USER: testdjereo
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/test

  django_checks:
    needs:
      - test
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/sys-check
        with:
          deploy: true

  containerise:
    needs:
      - django_checks
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo "REPO_NAME=${GITHUB_REPOSITORY@L}" >> $GITHUB_ENV
      - uses: ./.github/actions/containerise
        with:
          dockerfile: _deploy/deploy.Dockerfile
          username: ${{ github.actor }}
          password: ${{ github.token }}
          tags:
            ghcr.io/${{ env.REPO_NAME }}:latest,
            ghcr.io/${{ env.REPO_NAME }}:${{ github.ref_name }},

  deploy_latest_tag:
  # Prerequisites:
  #   - GH secrets (<https://github.com/albertomh/testdjereo/settings/secrets/actions>):
  #     - `DO_VPS_IP`: IPv4 address of the Digital Ocean Droplet (VPS)
  #     - `TESTDJEREO_BOT_PRIVATE_KEY`: private key for 'testdjereo_bot', `.ssh/testdjereo_bot_ed25519`
    needs:
      - containerise
    runs-on: ubuntu-24.04
    steps:
      - shell: bash
        env:
          DO_VPS_IP: ${{ secrets.DO_VPS_IP }}
          TESTDJEREO_BOT_PRIVATE_KEY: ${{ secrets.TESTDJEREO_BOT_PRIVATE_KEY }}
        run: |
            mkdir -p ~/.ssh
            echo "$TESTDJEREO_BOT_PRIVATE_KEY" > ~/.ssh/id_ed25519
            chmod 600 ~/.ssh/id_ed25519
            ssh -o StrictHostKeyChecking=no "testdjereo_bot@$DO_VPS_IP" \
            '/etc/testdjereo/blue_green_deployment'

  check_service_health:
  # Prerequisites:
  #   - GH secrets (<https://github.com/albertomh/testdjereo/settings/secrets/actions>):
  #     - `SERVICE_URL`: URL for the web service (WITHOUT trailing slash!)
    needs:
      - deploy_latest_tag
    runs-on: ubuntu-24.04
    steps:
      - name: Check service aliveness
        id: alive_check
        shell: bash
        env:
          SERVICE_URL: ${{ secrets.SERVICE_URL }}
        run: |
          response=$(wget --quiet --server-response --no-check-certificate -O - $SERVICE_URL/-/alive/ 2>&1)
          status_code=$(echo "$response" | grep -o "HTTP/[0-9.]* [0-9]*" | awk '{print $2}')
          if [[ "$status_code" == "200" ]]; then
              echo "🆗 /-/alive/ endpoint status: HTTP $status_code"
          else
              echo "🔴 Alive endpoint returned non-200 status: $status_code"
              exit 1
          fi
          echo "✅ Service is alive"

      - name: Check service health
        id: health_check
        shell: bash
        env:
          SERVICE_URL: ${{ secrets.SERVICE_URL }}
        run: |
          response=$(wget --quiet --server-response --no-check-certificate -O - "$SERVICE_URL/-/health/" 2>&1)
          status_code=$(echo "$response" | grep -o "HTTP/[0-9.]* [0-9]*" | awk '{print $2}')
          body=$(echo "$response" | sed -n '/^\r$/,$p' | tail -n +2)

          if [[ "$status_code" != "200" ]]; then
              echo "🔴 /-/health/ endpoint status: HTTP $status_code"
              echo "🔴 Response body:"
              jq <<< '$body'
              exit 1
          fi
          echo "✅ Service is healthy"
